# Generated by Django 4.2.30 on 2026-06-25 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='我的简历', max_length=200, verbose_name='简历标题')),
                ('summary', models.TextField(blank=True, default='', verbose_name='个人简介')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=10, verbose_name='状态')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='简历文件')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='文件名')),
                ('enabled_modules', models.JSONField(blank=True, default=list, help_text='用户启用的可配置模块列表，最多5个', verbose_name='启用模块')),
                ('module_data', models.JSONField(blank=True, default=dict, help_text='模块数据，键为模块名，值为内容文本', verbose_name='模块数据')),
                ('ai_processed', models.BooleanField(default=False, verbose_name='AI已处理')),
                ('ai_classification_result', models.JSONField(blank=True, default=dict, help_text='AI自动归类结果', verbose_name='AI归类结果')),
                ('visitor_enabled', models.BooleanField(default=False, help_text='是否启用了游客访问链接', verbose_name='游客链接启用')),
                ('visitor_token', models.CharField(blank=True, default='', help_text='游客访问唯一标识，用于URL路径', max_length=64, verbose_name='游客访问Token')),
                ('visitor_expires', models.DateTimeField(blank=True, help_text='游客链接过期时间', null=True, verbose_name='游客链接过期时间')),
                ('visitor_allow_download', models.BooleanField(default=False, help_text='是否允许游客下载PDF', verbose_name='允许游客下载')),
                ('public_modules', models.JSONField(blank=True, default=list, help_text='对游客公开的模块列表，为空则公开所有已启用模块', verbose_name='公开模块列表')),
                ('visitor_hr_enabled', models.BooleanField(default=False, help_text='是否启用HR模式（HR可通过链接使用AI助手）', verbose_name='HR模式启用')),
                ('visitor_ai_enabled', models.BooleanField(default=True, help_text='HR游客是否可使用AI功能', verbose_name='HR AI功能开关')),
                ('visitor_ai_quota', models.IntegerField(default=10, help_text='HR游客AI调用总配额', verbose_name='HR AI调用配额')),
                ('visitor_ai_used', models.IntegerField(default=0, help_text='HR游客已使用的AI调用次数', verbose_name='HR AI已用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='公司')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(blank=True, default='', verbose_name='工作描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='resumes.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('tag_type', models.CharField(choices=[('skill', '技能'), ('project', '项目'), ('certificate', '证书'), ('award', '获奖'), ('language', '语言'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='标签类型')),
                ('is_system', models.BooleanField(default=True, verbose_name='系统级标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['tag_type', 'name'],
                'unique_together': {('name', 'tag_type')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技能名称')),
                ('level', models.IntegerField(default=50, help_text='熟练度 0-100', verbose_name='熟练度')),
                ('category', models.CharField(blank=True, default='其他', max_length=50, verbose_name='分类')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'ordering': ['category', '-level'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='resumes.tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('role', models.CharField(blank=True, default='', max_length=100, verbose_name='担任角色')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('tech_stack', models.CharField(blank=True, default='', max_length=500, verbose_name='技术栈')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resumes.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '项目经历',
                'verbose_name_plural': '项目经历',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HRAiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_token', models.CharField(help_text='HR游客链接的token标识', max_length=64, verbose_name='访客Token')),
                ('call_type', models.CharField(choices=[('chat', 'AI咨询'), ('polish', '文本润色')], max_length=10, verbose_name='调用类型')),
                ('query_text', models.TextField(blank=True, default='', verbose_name='查询/润色内容')),
                ('response_text', models.TextField(blank=True, default='', verbose_name='AI回复内容')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='消耗Token数')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_ai_logs', to='resumes.resume', verbose_name='关联简历')),
            ],
            options={
                'verbose_name': 'HR AI使用日志',
                'verbose_name_plural': 'HR AI使用日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='学校')),
                ('degree', models.CharField(max_length=50, verbose_name='学位')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resumes.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_create', '创建用户'), ('user_update', '修改用户'), ('user_delete', '删除用户'), ('resume_update', '修改简历'), ('resume_delete', '删除简历'), ('tag_create', '创建标签'), ('tag_update', '修改标签'), ('tag_delete', '删除标签'), ('role_change', '角色变更'), ('other', '其他操作')], max_length=20, verbose_name='操作类型')),
                ('target_user', models.CharField(blank=True, default='', help_text='被操作的目标用户名', max_length=150, verbose_name='目标用户')),
                ('detail', models.TextField(blank=True, default='', help_text='操作详情描述', verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作管理员')),
            ],
            options={
                'verbose_name': '操作审计日志',
                'verbose_name_plural': '操作审计日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
