# Generated by Django 4.2.30 on 2026-07-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_create_resume_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePdfTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='模板名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='模板描述')),
                ('template_file', models.FileField(upload_to='resume_templates/', verbose_name='模板文件')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '简历模板',
                'verbose_name_plural': '简历模板',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
