# Generated by Django 4.2.30 on 2026-07-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumepdftemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='visitor_ai_system_prompt',
            field=models.TextField(blank=True, default='', help_text='访客AI模式的自定义System Prompt，为HR等访客提供关于开发者本人的详细背景信息', verbose_name='AI自定义提示词'),
        ),
    ]
