# Generated by Django 4.2.30 on 2026-06-25 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='查询内容')),
                ('response', models.TextField(blank=True, default='', verbose_name='回复结果')),
                ('intent', models.CharField(blank=True, default='', max_length=50, verbose_name='识别意图')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='消耗Token数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '查询日志',
                'verbose_name_plural': '查询日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(verbose_name='原始文本')),
                ('polished_text', models.TextField(blank=True, default='', verbose_name='润色结果')),
                ('module_name', models.CharField(blank=True, default='', max_length=50, verbose_name='所属模块')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时')], default='success', max_length=10, verbose_name='状态')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='消耗Token数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polish_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '润色日志',
                'verbose_name_plural': '润色日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('raw_text', models.TextField(blank=True, default='', verbose_name='原始文本')),
                ('classification_result', models.JSONField(blank=True, default=dict, verbose_name='归类结果')),
                ('modules_assigned', models.JSONField(blank=True, default=list, verbose_name='分配模块')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '归类日志',
                'verbose_name_plural': '归类日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
